export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  RESTAURANTS: '/restaurants',
  RESTAURANT: '/restaurants/:id',
  ORDERS: '/orders',
  ORDER_STATUS: '/orders/:id',
  ORDER_CONFIRM: '/orders/confirm',
  PROFILE: '/profile',
  FAVORITES: '/favorites',
  VENDOR_DASHBOARD: '/vendor',
  ADMIN: '/admin',
  STAFF_DASHBOARD: '/staff',
  DISPLAY_BOARD: '/display-board/:restaurantId',
};
